dist: xenial
language: python
sudo: false

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5" # travis numpy error

install:
  - pip install -e .[dev]

script:
  - tox

after_success:
  - coveralls
  - codecov

deploy:
  provider: pypi
  user: "$PYPI_USER"
  password: "$PYPI_PASS"
  distributions: "sdist bdist_wheel"
  skip_existing: true
  before_deploy: 'TAG="`git tag --points-at HEAD`"; grep "version=\"${TAG#v}\"" setup.py'
  on:
    tags: true
    if: tag =~ ^v
